repo: "Altinity/ClickHouse"
region: "us-east-1"
#vpc_id: "vpc-022419b07b58d216d"  # altinity-staging VPC
#subnet_id: "subnet-00f5e4fb0e8ef4649"  # altinity-staging-public-us-east-1a
vpc_id: "vpc-01c4c2f5a2656f34c"  # qa VPC
subnet_id: "subnet-0a9c364f785958571" # github-runners-subnet
# security_group_id: "sg-xxxxx"  # Optional: will create one if not specified
runners:
  - instance_type: "t4g.xlarge" 
    ami_id: "ami-022bbd2ccaf21691f"  # ARM64 Amazon Linux 2023
    count: 1
    labels:
      - self-hosted
      - Linux
      - ARM64
      - altinity-on-demand
      - altinity-startup-snapshot
      - altinity-image-arm-snapshot-22.04-arm-fail2ban
      - altinity-setup-fail2ban
      - altinity-type-cax11
      - altinity-style-checker-aarch64
      - altinity-image-arm-app-docker-ce
      - altinity-setup-regression
  - instance_type: "m6g.4xlarge"
    ami_id: "ami-022bbd2ccaf21691f"  # ARM64 Amazon Linux 2023
    count: 1
    labels:
      - self-hosted
      - Linux
      - ARM64
      - altinity-on-demand
      - altinity-startup-snapshot
      - altinity-image-arm-snapshot-22.04-arm-fail2ban
      - altinity-setup-fail2ban
      - altinity-type-cax41
      - altinity-func-tester-aarch64
      - altinity-image-arm-app-docker-ce