repo: "owner/repo"
vpc_id: "vpc-xxxxx"
subnet_id: "subnet-xxxxx"
#security_group_id: "sg-xxxxx" # Optional: will create one if not specified

# Default disk configuration (in GB)
# Can be overridden per runner
default_disk_size: 20  # 100 GB root volume
runners:
  - instance_type: "t4g.xlarge" 
    ami_id: "ami-07041441b708acbd6" # Ubuntu Server 24.04 LTS
    # disk_size: 150  # Optional: override default disk size (in GB)
    count: 1
    labels:
      - self-hosted
      - Linux
      - ARM64
      - type-t4g.xlarge
      - label1
      - label2
      - label3
  - instance_type: "m6g.4xlarge"
    ami_id: "ami-07041441b708acbd6" # Ubuntu Server 24.04 LTS
    count: 1
    labels:
      - self-hosted
      - Linux
      - ARM64
      - type-m6g.4xlarge
      - label1
      - label2
      - label3